# Configuration file for pre-commit (https://pre-commit.com/).
# Please run `pre-commit run --all-files` when adding or changing entries.

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
        types_or: [jupyter, markdown, python, shell]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - click != 8.1.0
          - stactools
          - types-python-dateutil
          - types-requests
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
