name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: stactools-goes
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Execute linters and test suites
        run: ./scripts/cibuild
