name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: stactools-goes
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Execute linters and test suites
        run: ./scripts/cibuild
